---
- name: Install Apache Web Server
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Deploy custom index page
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
